services:
    app_exception_listener:
        class: AppBundle\EventListener\ApiExceptionListener
        arguments:
        tags:
            - { name: "kernel.event_listener", event: "kernel.exception", method: "onKernelException" }