doctrine:
    dbal:
        driver: pdo_mysql
        host: "%env(MYSQL_HOST)%"
        port: '%database_port%'
        dbname: "%env(MYSQL_DATABASE)%"
        user: "%env(MYSQL_USER)%"
        password: "%env(MYSQL_PASSWORD)%"
        charset: UTF8
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            timestampable: true
            blameable: true