imports:
    - { resource: parameters.yml }
    - { resource: config/doctrine.yml }
    - { resource: security.yml }
    - { resource: "@AppBundle/Resources/config/services/general.yml" }
    - { resource: "@AppBundle/Resources/config/services/user.yml" }
    - { resource: "@AppBundle/Resources/config/services/terrain.yml" }

framework:
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        handler_id: session.handler.native_file
        save_path: "%env(SESSION_DIR)%"
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true