security:
    encoders:
        AppBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_USER:        [ROLE_USER]

    providers:
        user:
            entity: { class: Aisel\UserBundle\Entity\User, property: username }

    firewalls:
        user:
            pattern:             .*
            context:             user
            anonymous:           true

    access_control: