security:
    encoders:
        AppBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_USER:        [ROLE_USER]

    providers:
        user:
            entity: { class: AppBundle\Entity\User, property: username }

    firewalls:
        user:
            pattern:             .*
            context:             user
            anonymous:           true

    access_control:
        # API:user
        - { path: ^/api/user/settings, role: [ROLE_USER] }
        - { path: ^/api/user/login, allow_if: "is_anonymous() and !is_authenticated()" }
        - { path: ^/api/user/, allow_if: "is_anonymous() and !is_authenticated()" }

        # API:other
        - { path: ^/api/, role: [ROLE_USER] }
