app_action_post:
    path: /
    defaults: { _controller: AppBundle:Api/Action:post }
    methods:  [POST]


app_action_get:
    path: /{id}
    defaults: { _controller: AppBundle:Api/Action:get }
    methods:  [GET]