app_character_post:
    path: /
    defaults: { _controller: AppBundle:Api/Character:post }
    methods:  [POST]

app_character_get:
    path: /{id}
    defaults: { _controller: AppBundle:Api/Character:get }
    methods:  [GET]